### ISSUE TITLE
Wrong log directory

### ISSUE THREAD

**Issue by pm4rcin** [santigo-zero/csjarchlinux#1]
Hi, I think the log directory is wrong since it's normally on /var/log and you mount it to /log which doesn't exist. https://github.com/santigo-zero/csjarchlinux/blob/363e62c140891de6517fc86773a15acf93297b54/10-unattended.sh#L42

**Comment by santigo-zero** [comment]
Hello! Yes, you are right, /log doesn't exists, is there a way of acknowledge you for spotting the error?

**Comment by pm4rcin** [comment]
You don't have to acknowledge me really. Also about the /var/log I've read the [OpenSuse's plan](https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-filesystems.html#sec-filesystems-major-btrfs-suse) on subvolumes and they decided to make subvolume for the whole /var since there are many directories that change frequently like e.g. when you use VMs. I think that they have really good explanation for their layout.

**Comment by santigo-zero** [comment]
I was playing with VMs and MySQL so that's why I disabled CoW in the entire subvolume as well, I already pushed the latest changes and close this because it's pretty much resolved, thanks for the help!
