### ISSUE TITLE
Re-use home sub volume 

### ISSUE THREAD

**Issue by stephenseiber** [santigo-zero/csjarchlinux#5]
I think it might be possible to ask user if they want to reformat drive and if not format /boot and delete and create new non home sub volumes and keep the home volume untouched

**Comment by santigo-zero** [comment]
It's not really a feature that I will use, but in the case that anybody wants to add it at least for me it will be better to create a branch or a separate script (something like 10-preserve_home.sh), since I want to keep the code readable and concise.

**Comment by stephenseiber** [comment]
I don’t think I would use it either but have in the past and I’m sure some people would… second script works too I’ll probably do something similar with my own script

**Comment by santigo-zero** [comment]
Well, I don't have a way of testing if it's working properly or not, I already merged your pr, and I'll leave this issue open just in case.
